-- MySQL Script generated by MySQL Workbench
-- Wed Jun  9 03:17:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoProyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoProyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoProyecto` (
  `idtipoProyecto` INT NOT NULL AUTO_INCREMENT,
  `descripcionTipoProyecto` VARCHAR(20) NULL,
  PRIMARY KEY (`idtipoProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidadAcademica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`unidadAcademica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`unidadAcademica` (
  `idunidadAcademica` INT NOT NULL AUTO_INCREMENT,
  `descripcionUnidadAcademica` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idunidadAcademica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fuenteFinanciacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fuenteFinanciacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fuenteFinanciacion` (
  `idfuenteFinanciacion` INT NOT NULL AUTO_INCREMENT,
  `descripcionFuenteFinanciacion` VARCHAR(45) NOT NULL,
  `valorFuenteFinanciacioncol` INT NULL,
  PRIMARY KEY (`idfuenteFinanciacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombreDepartamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`municipio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `descripcionMunicipio` VARCHAR(45) NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `nombrePais` VARCHAR(45) NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`facultad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `descripcionFacultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoEntidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoEntidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoEntidad` (
  `idtipoEntidad` INT NOT NULL AUTO_INCREMENT,
  `descripcionTipoEntidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoEntidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entidadesParticipantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entidadesParticipantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entidadesParticipantes` (
  `identidadesParticipantes` INT NOT NULL AUTO_INCREMENT,
  `nombreEntidad` VARCHAR(45) NULL,
  `tipoEntidad_idtipoEntidad` INT NOT NULL,
  PRIMARY KEY (`identidadesParticipantes`),
  INDEX `fk_entidadesParticipantes_tipoEntidad1_idx` (`tipoEntidad_idtipoEntidad` ASC) ,
  CONSTRAINT `fk_entidadesParticipantes_tipoEntidad1`
    FOREIGN KEY (`tipoEntidad_idtipoEntidad`)
    REFERENCES `mydb`.`tipoEntidad` (`idtipoEntidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presupuestoProyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`presupuestoProyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`presupuestoProyecto` (
  `idpresupuestoProyecto` INT NOT NULL AUTO_INCREMENT,
  `rubroPresupuesto` VARCHAR(45) NULL,
  `totalRubro` INT NULL,
  `subtotalRubro` INT NULL,
  `entidadesParticipantes_identidadesParticipantes` INT NOT NULL,
  `desembolso` VARCHAR(45) NULL,
  `especie` VARCHAR(45) NULL,
  `detalladoPresupuesto` VARCHAR(45) NULL,
  PRIMARY KEY (`idpresupuestoProyecto`),
  INDEX `fk_presupuestoProyecto_entidadesParticipantes1_idx` (`entidadesParticipantes_identidadesParticipantes` ASC) ,
  CONSTRAINT `fk_presupuestoProyecto_entidadesParticipantes1`
    FOREIGN KEY (`entidadesParticipantes_identidadesParticipantes`)
    REFERENCES `mydb`.`entidadesParticipantes` (`identidadesParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`impactoProyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`impactoProyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`impactoProyecto` (
  `idimpactoProyecto` INT NOT NULL AUTO_INCREMENT,
  `descripcionImpacto` VARCHAR(45) NULL,
  `plazoDeAccion` VARCHAR(45) NULL,
  `indicadorVerificacble` VARCHAR(100) NULL,
  `supuesto` VARCHAR(100) NULL,
  PRIMARY KEY (`idimpactoProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `idPoyecto` INT NOT NULL AUTO_INCREMENT,
  `codigoProyecto` VARCHAR(30) NULL,
  `nombreProyecto` VARCHAR(45) NULL,
  `descripcionProyecto` LONGTEXT NULL,
  `valorProyecto` VARCHAR(45) NULL,
  `numeroConvenio` VARCHAR(45) NULL,
  `tipoProyecto_idtipoProyecto` INT NOT NULL,
  `semestreProyecto` VARCHAR(45) NULL,
  `anioProyecto` VARCHAR(45) NULL,
  `unidadAcademica_idunidadAcademica` INT NOT NULL,
  `facultad_idfacultad` INT NOT NULL,
  `duracionProyecto` INT NULL,
  `fechaInicioProyecto` DATE NULL,
  `fechaFinalizacionProyecto` DATE NULL,
  `resumenProyecto` LONGTEXT NULL,
  `costoProyecto` INT NULL,
  `proyectocol` VARCHAR(45) NULL,
  `fuenteFinanciacion_idfuenteFinanciacion` INT NOT NULL,
  `departamento_iddepartamento` INT NOT NULL,
  `municipio_idmunicipio` INT NOT NULL,
  `pais_idpais` INT NOT NULL,
  `facultad_idfacultad1` INT NOT NULL,
  `montoSolicitadoEntidades` VARCHAR(45) NULL,
  `fichaTecnicaDocumento` VARCHAR(45) NULL,
  `presupuestoProyecto_idpresupuestoProyecto` INT NOT NULL,
  `impactoProyecto_idimpactoProyecto` INT NOT NULL,
  PRIMARY KEY (`idPoyecto`),
  INDEX `fk_proyecto_tipoProyecto1_idx` (`tipoProyecto_idtipoProyecto` ASC) ,
  INDEX `fk_proyecto_unidadAcademica1_idx` (`unidadAcademica_idunidadAcademica` ASC) ,
  INDEX `fk_proyecto_fuenteFinanciacion1_idx` (`fuenteFinanciacion_idfuenteFinanciacion` ASC) ,
  INDEX `fk_proyecto_departamento1_idx` (`departamento_iddepartamento` ASC) ,
  INDEX `fk_proyecto_municipio1_idx` (`municipio_idmunicipio` ASC) ,
  INDEX `fk_proyecto_pais1_idx` (`pais_idpais` ASC) ,
  INDEX `fk_proyecto_facultad1_idx` (`facultad_idfacultad1` ASC) ,
  INDEX `fk_proyecto_presupuestoProyecto1_idx` (`presupuestoProyecto_idpresupuestoProyecto` ASC) ,
  INDEX `fk_proyecto_impactoProyecto1_idx` (`impactoProyecto_idimpactoProyecto` ASC) ,
  CONSTRAINT `fk_proyecto_tipoProyecto1`
    FOREIGN KEY (`tipoProyecto_idtipoProyecto`)
    REFERENCES `mydb`.`tipoProyecto` (`idtipoProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_unidadAcademica1`
    FOREIGN KEY (`unidadAcademica_idunidadAcademica`)
    REFERENCES `mydb`.`unidadAcademica` (`idunidadAcademica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_fuenteFinanciacion1`
    FOREIGN KEY (`fuenteFinanciacion_idfuenteFinanciacion`)
    REFERENCES `mydb`.`fuenteFinanciacion` (`idfuenteFinanciacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_departamento1`
    FOREIGN KEY (`departamento_iddepartamento`)
    REFERENCES `mydb`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_municipio1`
    FOREIGN KEY (`municipio_idmunicipio`)
    REFERENCES `mydb`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_facultad1`
    FOREIGN KEY (`facultad_idfacultad1`)
    REFERENCES `mydb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_presupuestoProyecto1`
    FOREIGN KEY (`presupuestoProyecto_idpresupuestoProyecto`)
    REFERENCES `mydb`.`presupuestoProyecto` (`idpresupuestoProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_impactoProyecto1`
    FOREIGN KEY (`impactoProyecto_idimpactoProyecto`)
    REFERENCES `mydb`.`impactoProyecto` (`idimpactoProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivelEscolaridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nivelEscolaridad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nivelEscolaridad` (
  `idnivelEscolaridad` INT NOT NULL AUTO_INCREMENT,
  `descripcionEscolaridad` VARCHAR(45) NOT NULL,
  `nemotecnicoEscolaridad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnivelEscolaridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documentoIdentidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`documentoIdentidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`documentoIdentidad` (
  `idDocumentoIdentidad` INT NOT NULL AUTO_INCREMENT,
  `descripcionDocumento` VARCHAR(20) NOT NULL,
  `nemotecnicoDocumento` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idDocumentoIdentidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sexo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sexo` (
  `idsexo` INT NOT NULL AUTO_INCREMENT,
  `descripcionSexo` VARCHAR(20) NOT NULL,
  `nemotecnicoSexo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idsexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estadoCivil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estadoCivil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estadoCivil` (
  `idestadoCivil` INT NOT NULL AUTO_INCREMENT,
  `descripcionEstadoCivil` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadoCivil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programaAcademico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`programaAcademico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`programaAcademico` (
  `idprogramaAcademico` INT NOT NULL AUTO_INCREMENT,
  `descripcionProgramaAcademico` VARCHAR(45) NULL,
  PRIMARY KEY (`idprogramaAcademico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupoInvestigacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grupoInvestigacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`grupoInvestigacion` (
  `idgrupoInvestigacion` INT NOT NULL AUTO_INCREMENT,
  `descripcionGrupoInvestigacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrupoInvestigacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vinculacionTipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`vinculacionTipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`vinculacionTipo` (
  `idvinculacionTipo` INT NOT NULL AUTO_INCREMENT,
  `descripcionTipoVinculacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idvinculacionTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`directorProyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`directorProyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`directorProyecto` (
  `idDirectorProyecto` INT NOT NULL AUTO_INCREMENT,
  `fechaNacimientoDirector` DATE NOT NULL,
  `documentoIdentidad_idDocumentoIdentidad` INT NOT NULL,
  `numeroDocumentoIdentiddad` VARCHAR(45) NOT NULL,
  `lugarExpedicionDocumento` VARCHAR(45) NOT NULL,
  `fechaExpedicionDocumento` DATE NOT NULL,
  `telefonoInvestigador` VARCHAR(45) NOT NULL,
  `estadoCivil_idestadoCivil` INT NOT NULL,
  `direccionResidencia` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL,
  `vinculacionTipo_idvinculacionTipo` INT NOT NULL,
  `codigoInstitucional` VARCHAR(45) NOT NULL,
  `unidadAcademica_idunidadAcademica` INT NOT NULL,
  `facultad_idfacultad` INT NOT NULL,
  `grupoInvestigacion_idgrupoInvestigacion` INT NOT NULL,
  `nivelEscolaridad_idnivelEscolaridad` INT NOT NULL,
  `proyecto_idPoyecto` INT NOT NULL,
  `sexo_idsexo` INT NOT NULL,
  `escolaridad_idescolaridad` INT NOT NULL,
  `numeroDocumentoIdentidad` VARCHAR(45) NOT NULL,
  `programaAcademico_idprogramaAcademico` INT NOT NULL,
  PRIMARY KEY (`idDirectorProyecto`),
  INDEX `fk_investigador_nivelEscolaridad1_idx` (`nivelEscolaridad_idnivelEscolaridad` ASC) ,
  INDEX `fk_investigador_documentoIdentidad1_idx` (`documentoIdentidad_idDocumentoIdentidad` ASC) ,
  INDEX `fk_investigador_proyecto1_idx` (`proyecto_idPoyecto` ASC) ,
  INDEX `fk_investigador_sexo1_idx` (`sexo_idsexo` ASC) ,
  INDEX `fk_investigador_estadoCivil1_idx` (`estadoCivil_idestadoCivil` ASC) ,
  INDEX `fk_investigador_programaAcademico1_idx` (`programaAcademico_idprogramaAcademico` ASC) ,
  INDEX `fk_investigador_grupoInvestigacion1_idx` (`grupoInvestigacion_idgrupoInvestigacion` ASC) ,
  INDEX `fk_investigador_unidadAcademica1_idx` (`unidadAcademica_idunidadAcademica` ASC) ,
  INDEX `fk_directorProyecto_vinculacionTipo1_idx` (`vinculacionTipo_idvinculacionTipo` ASC) ,
  INDEX `fk_directorProyecto_facultad1_idx` (`facultad_idfacultad` ASC) ,
  CONSTRAINT `fk_investigador_nivelEscolaridad1`
    FOREIGN KEY (`nivelEscolaridad_idnivelEscolaridad`)
    REFERENCES `mydb`.`nivelEscolaridad` (`idnivelEscolaridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_documentoIdentidad1`
    FOREIGN KEY (`documentoIdentidad_idDocumentoIdentidad`)
    REFERENCES `mydb`.`documentoIdentidad` (`idDocumentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_proyecto1`
    FOREIGN KEY (`proyecto_idPoyecto`)
    REFERENCES `mydb`.`proyecto` (`idPoyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_sexo1`
    FOREIGN KEY (`sexo_idsexo`)
    REFERENCES `mydb`.`sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_estadoCivil1`
    FOREIGN KEY (`estadoCivil_idestadoCivil`)
    REFERENCES `mydb`.`estadoCivil` (`idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_programaAcademico1`
    FOREIGN KEY (`programaAcademico_idprogramaAcademico`)
    REFERENCES `mydb`.`programaAcademico` (`idprogramaAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_grupoInvestigacion1`
    FOREIGN KEY (`grupoInvestigacion_idgrupoInvestigacion`)
    REFERENCES `mydb`.`grupoInvestigacion` (`idgrupoInvestigacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_unidadAcademica1`
    FOREIGN KEY (`unidadAcademica_idunidadAcademica`)
    REFERENCES `mydb`.`unidadAcademica` (`idunidadAcademica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_directorProyecto_vinculacionTipo1`
    FOREIGN KEY (`vinculacionTipo_idvinculacionTipo`)
    REFERENCES `mydb`.`vinculacionTipo` (`idvinculacionTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_directorProyecto_facultad1`
    FOREIGN KEY (`facultad_idfacultad`)
    REFERENCES `mydb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coautor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`coautor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`coautor` (
  `idCoautor` INT NOT NULL AUTO_INCREMENT,
  `nombreCoinvestigador` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `documentoIdentidad_idDocumentoIdentidad` INT NOT NULL,
  `numeroDocumentoIdentidad` VARCHAR(45) NOT NULL,
  `lugarExpedicionDocumento` VARCHAR(45) NULL,
  `numeroTelefonicoCoinvestigador` VARCHAR(45) NULL,
  `estadoCivil_idestadoCivil` INT NOT NULL,
  `direccionResideniaCoautor` VARCHAR(45) NULL,
  `correoElectronicoCoautor` VARCHAR(45) NULL,
  `vinculacionTipo_idvinculacionTipo` INT NOT NULL,
  `codigoInstitucional` VARCHAR(45) NULL,
  `unidadAcademica_idunidadAcademica` INT NOT NULL,
  `facultad_idfacultad` INT NOT NULL,
  `grupoInvestigacion_idgrupoInvestigacion` INT NOT NULL,
  `entidadesParticipantes_identidadesParticipantes` INT NOT NULL,
  `nivelEscolaridad_idnivelEscolaridad` INT NOT NULL,
  `sexo_idsexo` INT NOT NULL,
  `escolaridad_idescolaridad` INT NOT NULL,
  `dedicacionHoraProyecto` VARCHAR(3) NULL,
  PRIMARY KEY (`idCoautor`),
  INDEX `fk_coinvestigador_documentoIdentidad1_idx` (`documentoIdentidad_idDocumentoIdentidad` ASC) ,
  INDEX `fk_coinvestigador_nivelEscolaridad1_idx` (`nivelEscolaridad_idnivelEscolaridad` ASC) ,
  INDEX `fk_coinvestigador_sexo1_idx` (`sexo_idsexo` ASC) ,
  INDEX `fk_coinvestigador_estadoCivil1_idx` (`estadoCivil_idestadoCivil` ASC) ,
  INDEX `fk_coautores_vinculacionTipo1_idx` (`vinculacionTipo_idvinculacionTipo` ASC) ,
  INDEX `fk_coautores_unidadAcademica1_idx` (`unidadAcademica_idunidadAcademica` ASC) ,
  INDEX `fk_coautores_facultad1_idx` (`facultad_idfacultad` ASC) ,
  INDEX `fk_coautores_grupoInvestigacion1_idx` (`grupoInvestigacion_idgrupoInvestigacion` ASC) ,
  INDEX `fk_coautores_entidadesParticipantes1_idx` (`entidadesParticipantes_identidadesParticipantes` ASC) ,
  CONSTRAINT `fk_coinvestigador_documentoIdentidad1`
    FOREIGN KEY (`documentoIdentidad_idDocumentoIdentidad`)
    REFERENCES `mydb`.`documentoIdentidad` (`idDocumentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coinvestigador_nivelEscolaridad1`
    FOREIGN KEY (`nivelEscolaridad_idnivelEscolaridad`)
    REFERENCES `mydb`.`nivelEscolaridad` (`idnivelEscolaridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coinvestigador_sexo1`
    FOREIGN KEY (`sexo_idsexo`)
    REFERENCES `mydb`.`sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coinvestigador_estadoCivil1`
    FOREIGN KEY (`estadoCivil_idestadoCivil`)
    REFERENCES `mydb`.`estadoCivil` (`idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coautores_vinculacionTipo1`
    FOREIGN KEY (`vinculacionTipo_idvinculacionTipo`)
    REFERENCES `mydb`.`vinculacionTipo` (`idvinculacionTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coautores_unidadAcademica1`
    FOREIGN KEY (`unidadAcademica_idunidadAcademica`)
    REFERENCES `mydb`.`unidadAcademica` (`idunidadAcademica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coautores_facultad1`
    FOREIGN KEY (`facultad_idfacultad`)
    REFERENCES `mydb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coautores_grupoInvestigacion1`
    FOREIGN KEY (`grupoInvestigacion_idgrupoInvestigacion`)
    REFERENCES `mydb`.`grupoInvestigacion` (`idgrupoInvestigacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coautores_entidadesParticipantes1`
    FOREIGN KEY (`entidadesParticipantes_identidadesParticipantes`)
    REFERENCES `mydb`.`entidadesParticipantes` (`identidadesParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `idestudiante` INT NOT NULL AUTO_INCREMENT,
  `nombreEstudiante` VARCHAR(45) NOT NULL,
  `fechaNacimientoEstudiante` DATE NOT NULL,
  `documentoIdentidad_idDocumentoIdentidad` INT NOT NULL,
  `numeroIdentificacion` VARCHAR(45) NOT NULL,
  `fechaExpedicionDocumentoEst` DATE NOT NULL,
  `lugarExpedicionEst` VARCHAR(45) NOT NULL,
  `telefonoEstudiante` VARCHAR(45) NOT NULL,
  `estadoCivil_idestadoCivil` INT NOT NULL,
  `direccionResidenciaEst` VARCHAR(45) NOT NULL,
  `correoElectronicoEst` VARCHAR(45) NOT NULL,
  `codigoInstitucionalEst` VARCHAR(45) NOT NULL,
  `programaAcademico_idprogramaAcademico` INT NOT NULL,
  `facultad_idfacultad` INT NOT NULL,
  `grupoInvestigacion_idgrupoInvestigacion` INT NOT NULL,
  `entidadesParticipantes_identidadesParticipantes` INT NOT NULL,
  `escolaridad_idescolaridad` INT NOT NULL,
  `sexo_idsexo` INT NOT NULL,
  `nivelEscolaridad_idnivelEscolaridad` INT NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`idestudiante`),
  INDEX `fk_estudiante_programaAcademico1_idx` (`programaAcademico_idprogramaAcademico` ASC) ,
  INDEX `fk_estudiante_documentoIdentidad1_idx` (`documentoIdentidad_idDocumentoIdentidad` ASC) ,
  INDEX `fk_estudiante_sexo1_idx` (`sexo_idsexo` ASC) ,
  INDEX `fk_estudiante_nivelEscolaridad1_idx` (`nivelEscolaridad_idnivelEscolaridad` ASC) ,
  INDEX `fk_estudiante_estadoCivil1_idx` (`estadoCivil_idestadoCivil` ASC) ,
  INDEX `fk_estudiante_facultad1_idx` (`facultad_idfacultad` ASC) ,
  INDEX `fk_estudiante_pais1_idx` (`pais_idpais` ASC) ,
  INDEX `fk_estudiante_entidadesParticipantes1_idx` (`entidadesParticipantes_identidadesParticipantes` ASC) ,
  INDEX `fk_estudiante_grupoInvestigacion1_idx` (`grupoInvestigacion_idgrupoInvestigacion` ASC) ,
  CONSTRAINT `fk_estudiante_programaAcademico1`
    FOREIGN KEY (`programaAcademico_idprogramaAcademico`)
    REFERENCES `mydb`.`programaAcademico` (`idprogramaAcademico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_documentoIdentidad1`
    FOREIGN KEY (`documentoIdentidad_idDocumentoIdentidad`)
    REFERENCES `mydb`.`documentoIdentidad` (`idDocumentoIdentidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_sexo1`
    FOREIGN KEY (`sexo_idsexo`)
    REFERENCES `mydb`.`sexo` (`idsexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_nivelEscolaridad1`
    FOREIGN KEY (`nivelEscolaridad_idnivelEscolaridad`)
    REFERENCES `mydb`.`nivelEscolaridad` (`idnivelEscolaridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_estadoCivil1`
    FOREIGN KEY (`estadoCivil_idestadoCivil`)
    REFERENCES `mydb`.`estadoCivil` (`idestadoCivil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_facultad1`
    FOREIGN KEY (`facultad_idfacultad`)
    REFERENCES `mydb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `mydb`.`pais` (`idpais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_entidadesParticipantes1`
    FOREIGN KEY (`entidadesParticipantes_identidadesParticipantes`)
    REFERENCES `mydb`.`entidadesParticipantes` (`identidadesParticipantes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_grupoInvestigacion1`
    FOREIGN KEY (`grupoInvestigacion_idgrupoInvestigacion`)
    REFERENCES `mydb`.`grupoInvestigacion` (`idgrupoInvestigacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`poblacionBeneficiaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`poblacionBeneficiaria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`poblacionBeneficiaria` (
  `idpoblacionBeneficiaria` INT NOT NULL AUTO_INCREMENT,
  `poblacionBeneficiariacol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpoblacionBeneficiaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_has_poblacionBeneficiaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`proyecto_has_poblacionBeneficiaria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_has_poblacionBeneficiaria` (
  `proyecto_idPoyecto` INT NOT NULL,
  `poblacionBeneficiaria_idpoblacionBeneficiaria` INT NOT NULL,
  `cantidadPobllacionBeneficiar` INT NULL,
  PRIMARY KEY (`proyecto_idPoyecto`, `poblacionBeneficiaria_idpoblacionBeneficiaria`),
  INDEX `fk_proyecto_has_poblacionBeneficiaria_poblacionBeneficiaria_idx` (`poblacionBeneficiaria_idpoblacionBeneficiaria` ASC) ,
  INDEX `fk_proyecto_has_poblacionBeneficiaria_proyecto1_idx` (`proyecto_idPoyecto` ASC) ,
  CONSTRAINT `fk_proyecto_has_poblacionBeneficiaria_proyecto1`
    FOREIGN KEY (`proyecto_idPoyecto`)
    REFERENCES `mydb`.`proyecto` (`idPoyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_has_poblacionBeneficiaria_poblacionBeneficiaria1`
    FOREIGN KEY (`poblacionBeneficiaria_idpoblacionBeneficiaria`)
    REFERENCES `mydb`.`poblacionBeneficiaria` (`idpoblacionBeneficiaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultadoProyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`resultadoProyecto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`resultadoProyecto` (
  `idresultadoProyecto` INT NOT NULL,
  `descripcionResultado` VARCHAR(45) NULL,
  `indicardorResultado` VARCHAR(45) NULL,
  `beneficiario` VARCHAR(45) NULL,
  `proyecto_idPoyecto` INT NOT NULL,
  PRIMARY KEY (`idresultadoProyecto`),
  INDEX `fk_resultadoProyecto_proyecto1_idx` (`proyecto_idPoyecto` ASC) ,
  CONSTRAINT `fk_resultadoProyecto_proyecto1`
    FOREIGN KEY (`proyecto_idPoyecto`)
    REFERENCES `mydb`.`proyecto` (`idPoyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
